### ISSUE TITLE
MVP

### ISSUE THREAD

**Issue by omgitstom** [stormpath/stormpath-sdk-android#1]
Support for:
- [x] Initialization of the SDK to connect to a Stormpath Integration
- [x] Create Account
- [x] Login
- [x] Reset Password
- [x] Refresh an Access Token
- [x] Get an Access Token
- [x] Email Verification

Android SDK should allow for configuration for the endpoint of the integration (for example:  https://whatever.com) and routes for individual functionality should be configured.  By default, if the routes are not configured, the Stormpath SDK should default to the defaults for the integration.

Once an Access Token / Refresh Token combination is received, they should be stored in Shared Preferences on the device.

**Comment by omgitstom** [comment]
Basic
1. Must support the use Maven / Gradle
2. Use OkHTTP
3. Use interfaces for loggings and storage that can be easy to replace

Initialization
1. Configuration should be doing initialization of the SDK

**Comment by dogeared** [comment]
addressed by #6
