### ISSUE TITLE
Register callback error in ApiManager

### ISSUE THREAD

**Issue by ksilha** [stormpath/stormpath-sdk-android#32]
In API manager, in the call back for a successful registration, an error gets thrown after new Account gets created.

On line 24 of ApiManager.java:
String sessionTokens[] = {"PLACEHOLDER"};
String accessToken = sessionTokens[0];
String refreshToken = sessionTokens[1];

Only one element gets set in sessionTokens, so sessionTokens[1] throws error:
java.lang.ArrayIndexOutOfBoundsException: length=1; index=1

**Comment by edjiang** [comment]
Hey @ksilha: thanks for letting me know! I missed something when making the 2.0 release, and need to get it fixed =] Will do within the next 24 hours.

**Comment by edjiang** [comment]
Should be fixed! Check out 2.0.1 on gradle. Sorry about this!

**Comment by ksilha** [comment]
Thank you @edjiang ! The fix works great!
