### ISSUE TITLE
Activities and Fragments for Login

### ISSUE THREAD

**Issue by omgitstom** [stormpath/stormpath-sdk-android#4]
I'm curious what a generic activity will look like for Android for login.  This login activity should be simple to use and customize.  It should handle storing the access / refresh token on success and displaying error messages correctly.

Once we get a handle for this for login, we can do the same across other views

**Comment by ericlw** [comment]
Generic + Customizability fixed by 99e68590ec19e4a22d0f88540cbf91b75a611e1e and 8a9dcc6fba85a4f0ec36985fe826fa1e0e0bf4df
